### PR TITLE
Added Sample Cloudinary Service

### PR DESCRIPTION
**Pull request by Moses-Padirolu**

### CODE REVIEW

**Comment by hrit2773** [comment]
@Moses-Padirolu did you watch the cloudinary part of the video and did it

**Comment by Moses-Padirolu** [comment]
i didnt watch that video , i took help of chatgpt to set up environment. shall i go through that video and set the environment.

**Comment by hrit2773** [comment]
@Moses-Padirolu seems ok if its working no need if its working then its okay

**Comment by hrit2773** [comment]
https://github.com/hrit2773/Imagify-SaaS-Frontend/issues/1

**Pull request merged**
